### PR TITLE
Pass fix31 (not short) height to external vst_height()

### PR DESCRIPTION
**Pull request by chrisridd**
This should fix your code @mfro0 ! Apologies for missing this case.

### CODE REVIEW

**Comment by mfro0** [comment]
way better - many thanks!

**Comment by mfro0** [comment]
there is still something not quite right.

Running on hatari with the bitplane driver, TT emulation (640x480*4 Planes), the AES for some reason use the small system font instead of the 16x8 font normally used:

grab0002
(note menu bar and window title)

**Comment by chrisridd** [comment]
I did notice the 8x8 font in the screenshot, but wasn't sure if that was expected. I'll put a hatari installation together to reproduce this.

**Comment by mfro0** [comment]
I'm wondering if it's caused by the bitplane.sys driver that uses more functionality from the ROM VDI than the other drivers.

Maybe the ROM driver sees the changed structure field value somehow?

**Comment by chrisridd** [comment]
That's an interesting idea. The contents of the `Fontheader ` `size/dummy` field are still flipped, so if something's still assuming those bytes are the size they should be getting the right data. Similarly, `insert_font()` just mechanically changes from checking `size` to `extra.size` so that should be OK too.

The emutos aes sources didn't give me any insights as to what it was calling to setup the font. Everything seems to rely on defaults :-(

I'm having trouble getting a hatari setup (using [hatari-2.3.1 ](https://download.tuxfamily.org/hatari/2.3.1/)) that boots fvdi successfully... do you have any tips or sample configs?

**Comment by mfro0** [comment]
[fvdi_test.tar.gz](https://github.com/freemint/fvdi/files/8705472/fvdi_test.tar.gz)

This is my test directory. After unpacking, just start hatari from that directory with `hatari -c tt.cfg`. You'll need to adapt the symbolic links to `fvdi_gnu.prg` (inside the auto folder) and `bitplane.sys` (in the gemsys folder) and the paths in the .cfg file (EmuTOS image and others) to your dev setup.

Then it should 'just work ™'. Hopefully.f

**Comment by mfro0** [comment]
any progress on this?
Might be better to reverse previous changes?

**Comment by chrisridd** [comment]
Sorry, I've been out of action for a bit. I have some ideas and will start investigating this weekend while I'm still (grr) isolating.

**Comment by mfro0** [comment]
Don't worry, sometimes life gets in the way. Wish you a speedy recovery.

**Comment by mfro0** [comment]
I have now reverted both fix31 commits as others have problems with wrong font heights in the desktop as well.
Will be revisited if you (or somebody) can come up with a solution.

**Comment by chrisridd** [comment]
Understood, and it was the right call to make. Clearly the change was too ambitious :-(

**Pull request merged**
